.\" groff -man -Tascii foo.1
.TH SESSIONINSTALLER 1 "April 2010" Linux "User manual"
.SH NAME
gst-install \- installs missing GStreamer plugins
.SH SYNOPSIS
.B gst-install
.RI [ OPTIONS ]
plugin
.B ...
.SH DESCRIPTION
.B Gst-install
makes use of the PackageKit session D-Bus interface to install missing
GStreamer plugins, e.g. encoders, decoders or URI handlers. It isn't supposed
to be executed directly but instead by the 
.BR gst_install_plugins_async " and " gst_install_plugins
functions of the GStreamer base library
.BR gstpbutilsinstallplugins .

PackageKit or the alternative session-installer implementation will handle
the complete installation process with confirmation, progress and error
dialogs.

See the documentation of 
.B gstpbutilsinstallplugins
for the argument construction and exit states.
.SH OPTIONS
.IP --transient-for
The X Window ID of the window which should be used as parents for the dialogs
.SH DIAGNOSTICS
None yet.
.SH HOMEPAGE
https://launchpad.net/sessioninstaller
.SH BUGS
You can report bugs at the Launchpad site of aptdaemon:
https://bugs.launchpad.net/sessioninstaller/+filebug
.SH AUTHOR
Sebastian Heinlein <devel at glatzor dot de>
.SH SEE ALSO
.BR aptd (1) " session-installer" (1)
