#!/bin/sh
# postinst script for gstreamer0.10-packagekit

set -e

update-alternatives --install /usr/bin/gstreamer-codec-install \
		    gstreamer-codec-install \
		    /usr/bin/gst-install 80 || true

#DEBHELPER#

exit 0

